### ISSUE TITLE
Http404: No se han encontrado Entrada que coincidan con la consulta

### ISSUE THREAD

**Issue by jstoledano** [jstoledano/nspaces#37]
View details in Rollbar: [https://rollbar.com/ine/nspaces/items/38/](https://rollbar.com/ine/nspaces/items/38/)

```
Traceback (most recent call last):
  File "/home/javier/.pyenv/versions/3.6.2/envs/yo/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/javier/.pyenv/versions/3.6.2/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/javier/.pyenv/versions/3.6.2/envs/yo/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/javier/.pyenv/versions/3.6.2/envs/yo/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/javier/projects/nspaces/src/apps/blog/views.py", line 100, in get
    self.object = self.get_object()
  File "/home/javier/.pyenv/versions/3.6.2/envs/yo/lib/python3.6/site-packages/django/views/generic/detail.py", line 56, in get_object
    {'verbose_name': queryset.model._meta.verbose_name})
Http404: No se encontró ningún Entrada coincidente con la consulta
```

**Comment by jstoledano** [comment]
Se cerró con la #38
